### ISSUE TITLE
list index out of range

### ISSUE THREAD

**Issue by itrack** [dexterke/plugin.video.digi.ro-online#3]
**It does not work for me, in logs I found this error:**

> 
> 2019-06-23 21:07:02.294 T:18616   ERROR: EXCEPTION Thrown (PythonToCppException) : -->Python callback/script returned the following error<--
>                                              - NOTE: IGNORING THIS CAN LEAD TO MEMORY LEAKS!
>                                             Error Type: <type 'exceptions.IndexError'>
>                                             Error Contents: list index out of range
>                                             Traceback (most recent call last):
>                                               File "C:\Users\astoi\AppData\Roaming\Kodi\addons\plugin.video.digi.ro-online\default.py", line 572, in <module>
>                                                 parseInput(url)
>                                               File "C:\Users\astoi\AppData\Roaming\Kodi\addons\plugin.video.digi.ro-online\default.py", line 459, in parseInput
>                                                 link = processHTML(url)
>                                               File "C:\Users\astoi\AppData\Roaming\Kodi\addons\plugin.video.digi.ro-online\default.py", line 426, in processHTML
>                                                 digiHost = str(re.compile('https://(.+?)/').findall(link)[0])
>                                             IndexError: list index out of range
>                                             -->End of Python script error report<--

**Comment by dexterke** [comment]
I've never tested this plugin on Windows, tested on GNU Linux (Ubuntu 14-16), OSMC 16-19(RaspberryPi), Android 8 and MacOS 10.10 - 10.11; pyhton code, however, should work on windows as well, I'm gonna need more info, there is not much here to work with.

Please provide the following details:
- This plugin DOES NOT work without a valid account, so make sure your DIGI.RO login credentials are valid, confirm that you are able to login and watch provided TV channels on https://www.digionline.ro.
- MS Windows version/arch and version of Kodi the plugin fails on
- Provide debug logs: Videos -> Add-ons -> right click on Digi.ro-Online (select settings) -> Debug options -> Select 'Enable debug'
Run the plugin and see it fails, send me an archive of YOUR_KODI_HOME\userdata\addon_data/plugin.video.digi.ro-online\ directory   (please remove your Digi.ro login credentials from settings.xml  and from plugin_video_digionline.ro.log before sending)

**Comment by itrack** [comment]
I get the same error on Android TV.
I will retry with your proposed and I will return with clarifications

**Comment by dexterke** [comment]
YOUR_KODI_HOME/userdata/addon_data/plugin.video.digi.ro-online/plugin_video_digionline.ro.log should provide more clues

**Comment by itrack** [comment]
Hi,
It was because I have a Digi Romania account, not Digi Online.

I made a fork for those with the same situation:
https://github.com/itrack/plugin.video.digi.ro-online

It is made to work only with Digi Romania account

**Comment by itrack** [comment]
I do not know python so well that I can make a flexible solution, maybe you could do that :D

**Comment by dexterke** [comment]
Hmm, interesting. I had no idea there are other ways to access the portal. AFAIK the changes would be simple:
```
33c33
< loginURL = 'https://www.digionline.ro/auth/login'
---
> loginURL = 'https://www.digionline.ro/auth/login-digiro'
269c269
< 	  post_data={'form-login-email': login_User, 'form-login-password': login_Password}
---
> 	  post_data={'form-login-digiro-email': login_User, 'form-login-digiro-password': login_Password}
```
I think I could merge the changes, add support for both.

**Comment by itrack** [comment]
Would be great! 

Thanks for your advice with log, I noticed where the block :D

**Comment by dexterke** [comment]
v 1.2.0 - Added support for DIGI-Romania acounts login
I can only test with DIGI-Online account, but I followed your instructions for DIGI-Romania.
@itrack please test and provide feedback.

**Comment by crisp2u** [comment]
Perfect! Thanks. Let me know if you need any further help, maybe setting up releases or a repo.

**Comment by dexterke** [comment]
well... is it working or not ? I cannot test both scenarios. if the new version works, there's nothing more to do here, I would close the case, enjoy the summer  - happy days for everyone :)

**Comment by crisp2u** [comment]
@dexterke Sorry, I though I was clear. I tested the DIGI-Romania account and it works. I guess you tested DIGI-Online. So, enjoy the summer, at least until I ask for better UI on switching the login type and parental control support :)
