### ISSUE TITLE
Channels not working on Android

### ISSUE THREAD

**Issue by adi2kx** [dexterke/plugin.video.digi.ro-online#4]
Hello,
It looks like the channels are no longer working. The website and mobile app were recently updated. Would it be possible to update the add-on?
Thank you

**Comment by dexterke** [comment]
You'll have to do better than 'looks like the channels are no longer working', what exactly is not working?
I checked all channels and could not find anything wrong. Please provide more details, e.g. what is your OS/platform, type of account (Digi-Online/Digi-Romania), is this something that used to work and stopped working for you, where are you accessing from (inside RDS network /VPN), etc.

Have you seen this ?
Readme: https://github.com/dexterke/plugin.video.digi.ro-online/blob/master/README.md

Make sure to use the latest version of this plugin:
Go to https://github.com/dexterke/plugin.video.digi.ro-online
`Clone or download` -> `Download zip`

**Comment by adi2kx** [comment]
Hello,
Thank you for your prompt reply. I apologize for assuming the channels are no longer working. I have Kodi installed on an Android box. After the plugin stopped working for me, I tested the official Digi Online app on the same box and it worked fine, which made me believe there was something wrong with the plugin itself. After getting your reply I also tested your plugin on a Windows PC and it worked fine. It seems to not work only on the Android box. I have reinstalled the latest Kodi and the latest version of your plugin on the Android box but I have the same issue. It is configured properly and the box is connected to the same home network as the PC.
The Kodi logs show the following errors:
ERROR: CCurlFile::Stat - Failed: HTTP response code said error(22)
ERROR: CCurlFile::FillBuffer - Failed: HTTP returned error 403
From what I found out, error 22 means the HTTP server returns an error code that is >= 400, and error 403 means that access is denied. I am not sure why I'm getting these errors. It worked fine not so long ago. If you have any advice or a solution based on your experience with Kodi, I would really appreciate it.
Thank you

**Comment by dexterke** [comment]
Did some digging,  https://kodi.tv/blog
and came across this link https://kodi.tv/article/kodi-19-python-3-goes-live

Are you using Kodi 19.X? This would explain the problem, I wrote the plugins using python2 (no longer supported) so I will have to re-write the plugin for python3. If that is the case, you should try installing an older version e.g. 18.4 of Kodi, see if that works for you.

**Comment by adi2kx** [comment]
I did some more troubleshooting and came up with the following results:

Initially, I was running Kodi 18.4 and plugin v1.2.0 when I started having the issue.
I then upgraded to Kodi 18.5 and had the same issue.
I downgraded to Kodi 18.3 with plugin v.1.1.0 and v1.2.0 and had the same issue.
I tested the digionline website in Chrome on the Android box and it worked fine.
I tested the plugin on an Android tablet and had the same issue. The official app works fine on the same Android tablet.

I was reading on a forum that the UserAgent may cause something like this, but that wouldn't explain why it's still working fine on Windows. The UserAgent is coded in the plugin and doesn't change based on platform, at least not in this plugin.

Do you think there is something specific that needs to be coded in for Android devices?

**Comment by dexterke** [comment]
Enable plugin debug: 
`Kodi` -> `Videos` -> `Addons` -> `Digi.ro-Online` -> `Settings` -> `Debug Options` -> `Enable Debug`
This will create a file named 

`Android/data/org.xbmc.kodi/files/.kodi/userdata/addon_data/plugin.video.digi.ro-online/plugin_video_digionline.ro.log`

Userdata folder documented here: https://kodi.wiki/view/Userdata#Android_location

There seems to be an issue on Android only. I tested the plugin on a XIAOMi MiBOX (Offical AndroidTV OS), using KODI 18.5 and I ran in the same issues as you have. However, according to my logs, the plugin seems to achieve everything it is supposed to do: 

1. authenticate
2. acquire the playlist 
3. pull out the URL for playback. 
4. pass the playlist/URL onto KODI's video player 

The issue seems to be (at least, that is what I believe now) with Kodi not playing the provided URL. 

I have Kodi 18.5 running on Ubuntu, OSMC (RaspberryPI), MacOS without any issues, The only problems so far occur on Android.

**Comment by adi2kx** [comment]
Sorry for the delayed response. I got a log for you. I removed my login information. Is there any other identifiable data within the log? How would you like me to send it to you?

**Comment by dexterke** [comment]
email the logs to dexterkexnet@yahoo.com

**Comment by adi2kx** [comment]
Sent you the logs. Thanks

**Comment by dexterke** [comment]
I've looked at the log, looks the same as for me: according to the log, the plugin achieves its task: acquire session cookies, log in to digionline.ro and extract the playlist for a given TV channel, it even saves the m3u playlist:
```
#EXTM3U
#EXT-X-VERSION:3
#EXT-X-STREAM-INF:BANDWIDTH=3500330,CODECS="avc1.77.41,mp4a.40.2",RESOLUTION=1024x576
chunklist_w783676949.m3u8?is=29&src=app&t=00000000000000000000000000000000&s=site&sn=digionline.ro&p=browser
```

The issue seems to occur when passing the playlist onto Kodi's video player, however, no error is reported by the plugin
```
xbmc.Player().play(https://edge24.rcs-rds.ro/digiedge2/b1tvehq/index.m3u8?is=29&src=app&t=00000000000000000000000000000000&s=site&sn=digionline.ro&p=browser,<xbmcgui.ListItem object at 0xc9330c90>)
```
XBMC player is documented here: https://codedocs.xyz/xbmc/xbmc/group__python___player.html

I don't yet understand how that is any different on Android to other Operating Systems, and given that this issue occurs on Android only, does not make it easy to debug.

**Comment by a-mad-eus** [comment]
Hi dexterke,
I believe I have the same issue as adi2kx. 
I have Kodi v18.5  Leia installed on an Amazon Fire TV Stick 4k and Digi.ro-Online configured with my Digi-Online account data. I use an OpenVPN client installed on the Fire TV Stick to connect to my private VPN server, located in the RDS network. I am able to open all the Digi channels, but the video stream doesn't start. There is only 1 cannel for which the video stream starts: Digi24 
If it would help, I can email you the log file. Please let me know.

**Comment by nextshell** [comment]
Some times you get that when you've reached the max limit of authentication, check that first!

**Comment by a-mad-eus** [comment]
Thank you for the quick reply. I checkt and the limit (5 devices) isn't reached.
I also don't see any error in the log. This is the last log entry:
`processHTML received data: ---------- 
#EXTM3U
#EXT-X-VERSION:3
#EXT-X-STREAM-INF:BANDWIDTH=3488042,CODECS="avc1.77.41,mp4a.40.2",RESOLUTION=1024x576
chunklist_w1976754237.m3u8?is=29&src=app&t=00000000000000000000000000000000&s=site&sn=digionline.ro&p=browser

parseInput link https://edge30.rcs-rds.ro/digiedge2/b1tvehq/index.m3u8?is=29&src=app&t=00000000000000000000000000000000&s=site&sn=digionline.ro&p=browser
xbmc.Player().play(https://edge30.rcs-rds.ro/digiedge2/b1tvehq/index.m3u8?is=29&src=app&t=00000000000000000000000000000000&s=site&sn=digionline.ro&p=browser,<xbmcgui.ListItem object at 0x83ab1770>)
--------------------------------------------`

**Comment by dexterke** [comment]
Your log shows the media playlist aquired by the plugin, you could pass that on to any network media player (along with the http session variables), the plugin works as designed up to the point when passing the acquired playlist to the actual player,  xbmc.Player() then fails with HTTP error 403 (Forbidden).
I currently have no idea what and how to fix, I suspect Android OpenSSL. The fact that the issue occurs only on Android (basically a lobotomized Linux) makes it difficult for me to debug and test.

**Comment by zedatgithub** [comment]
First of all Thanks for this great plugin !

I had the same issue that only Digi24 was working on Android S912 TV Box

i was able to fix the issue by changing the row 429 
                            link = ''.join(('https:', link))
to
                            link = ''.join(('https:', link + '|User-Agent=' + userAgent + '&Referer=' + url))


i know its not a pretty fix but you understand what it does and you can implement in a better way

**Comment by dexterke** [comment]
@zedatgithub  - Thanks a million for helping out :) 
So far, my efforts in trying to debug on Android led me nowhere and SSL did not make my life easier in that regard either.

# You are the man @zedatgithub - Big kudos to you !!!

**Comment by adi2kx** [comment]
@zedatgithub - Thank you for providing the fix for this issue.
@dexterke - Thank for your time and effort you put into this, as well as your prompt responses.
I've tested the latest version and the issue is now resolved, as well as there are new channels added. I renamed this thread to match the issue and will close it.
