### ISSUE TITLE
Add 'amc' channel

### ISSUE THREAD

**Issue by cralin** [dexterke/plugin.video.digi.ro-online#8]
Hi,

Could you please add the 'amc' channel or allow my user to push a feature branch and open a PR ?

Here the changes in my feature branch:

diff --git a/default.py b/default.py
index c33031c..e3bf4e4 100644
--- a/default.py
+++ b/default.py
@@ -116,6 +116,7 @@ def ROOT():
     addDir('Comedy Central', 'https://www.digionline.ro/filme/comedy-central', setIcon('Comedy-Central.png'))
     addDir('TNT', 'https://www.digionline.ro/filme/tnt', setIcon('TNT2.png'))
     addDir('TV1000', 'https://www.digionline.ro/filme/tv-1000', setIcon('TV1000.png'))
+    addDir('AMC', 'https://www.digionline.ro/filme/amc', setIcon('AMC.png'))
     addDir('Epic Drama', 'https://www.digionline.ro/filme/epic-drama', setIcon('Epic-Drama.png'))
     addDir('Bollywood TV', 'https://www.digionline.ro/filme/bollywood-tv', setIcon('BollywoodTV.png'))
 
diff --git a/resources/media/AMC.png b/resources/media/AMC.png
new file mode 100644
index 0000000..e2a30e6
Binary files /dev/null and b/resources/media/AMC.png differ

**Comment by dexterke** [comment]
@cralin  thank you for bringing this up. I have just added the new channels. 
Please test and let me know.

**Comment by cralin** [comment]
Hi,

Works for the new channels added.

In my online account I can see the cinemax and cinemax-2 channels and they can be played in the web browser.

Could you please add them as well in the list of available channels ?

Thank you.

**Comment by dexterke** [comment]
- TV channels listed below do not work yet as they are DRM protected:
    Cinemax
    Cinemax2
    FilmNow
    HBO Ro
    HBO 2
    HBO 3

They may work in your browser (because DRM allows it) but this plugin (as it is today) cannot play them. Feel free to test yoruself by un-commenting lines 128 - 135 in `default.py` - the above mentioned channels are commented our because they don't work.

**Comment by cralin** [comment]
@dexterke ,
I've enabled the debug logging in the add-on and tried to play again the cinemax stream.

Obviously, it failed to play the stream (no surprise here), but the interesting part is what actually gets written in the log file.

In the log file I can see this:
> processHTML received data: ---------- 
> {"meta":{"version":12,"result_code":0,"result_info":"OK","result_message":"","data":0,"error":0},"error":{"error_code":0,"error_message":"","error_details":""},"data":{"content":{"drm":"w","stream.type":"dash","stream.manifest.type":"mpd","stream.manifest.url":"https:\/\/edgen24.rcs-rds.ro\/dash\/97\/97.mpd","widevine.proxy":"https:\/\/wvp-cdn.rcs-rds.ro\/proxy"}}}
> processHTML json stream_url: {u'meta': {u'version': 12, u'result_info': u'OK', u'error': 0, u'data': 0, u'result_message': u'', u'result_code': 0}, u'data': {u'content': {u'stream.manifest.type': u'mpd', u'stream.manifest.url': u'https://edgen24.rcs-rds.ro/dash/97/97.mpd', u'drm': u'w', u'stream.type': u'dash', u'widevine.proxy': u'https://wvp-cdn.rcs-rds.ro/proxy'}}, u'error': {u'error_details': u'', u'error_message': u'', u'error_code': 0}}
> 

That looks like it is a Widevine DRM content.
Kodi 18 has implemented support for playback of Widevine DRM content via the inputstream.adaptive add-on.

According to examples [here](https://github.com/peak3d/inputstream.adaptive/blob/master/README.md) it should be fairly easy to play that DRM enabled (mpd) stream.

[This post](https://forum.kodi.tv/showthread.php?tid=330507&pid=2722301#pid2722301) shows how to do it from within an add-on.

Would you be willing to extend your add-on to support those DRM enabled channels as well ?

**Comment by dexterke** [comment]
I am aware of recent versions of KODI supporting DRM, but adding DRM feature would be a low priority task for me at the moment.
