### ISSUE TITLE
Addon configuration?

### ISSUE THREAD

**Issue by lexanu** [dexterke/plugin.video.digi.ro-online#9]
Do we need do configure somehow the addon after installing? I remember that a while back it was "plug'n play". Now it says that i have to configure it and i don't know what to do. Thank you!

**Comment by dexterke** [comment]
@lexanu Yes, you need to configure this add-on. There is nothing special about this, configure it as you would configure any Kodi add-on. Each skin is different, but the general idea would be to go to Kodi -> Videos -> Video Add-ons, select plugin.video.digi.ro-online and avail of the context menu (right click, long press for Android or keyboard `c`)
Have a look here, see if it helps: https://www.howtogeek.com/76240/the-how-to-geek-guide-to-xbmc-add-ons/

**Comment by lexanu** [comment]
Thank you! Now it is configured. It would be helpful if a pop-up could appear when inserted username and password are not correct. Thank you again!
